let definitions = {
	"0-click connect": "A feature that allows users to connect their hardware wallet to a compatible service or platform without any manual action or confirmation, enhancing the user experience and accessibility.",
    "affiliate link": "A unique URL provided to affiliates that tracks the referral of customers to Ledger's products, often used in marketing actions.",
    "agreement framework": "A set of clarified roles and responsibilities between Ledger and third-party developers during integration.",
    "api": "Application Programming Interface, a set of routines, protocols, and tools for building software and applications.",
    "app deployment process": "Ledger will fork the application's repository to manage the deployment process, which includes testing and modifications before the application is ready for production.",
    "application architecture": "The structure and data flow of the application that integrates with the Ledger device.",
    "backend": "The part of a computer system or application that is not directly accessed by the user, typically responsible for storing and managing data.",
    "bip 39": "Bitcoin Improvement Proposal 39, a standard that defines how to generate the mnemonic phrase that is used to create the master seed in a wallet.",
    "bitcoin/ethereum api": "Specific APIs provided by Ledger for integrating Bitcoin and Ethereum applications with the Ledger device.",
    "blind signing": "A security risk where a user signs a transaction with a hardware wallet without being able to verify all of its details, due to limited information being displayed on the device.",
    "blockchain": "A system of recording information in a way that makes it difficult or impossible to change, hack, or cheat the system.",
    "bolos": "Blockchain Open Ledger Operating System, a secure and flexible operating system developed by Ledger for its hardware wallets.",
    "bolos sdk": "Software Development Kit for BOLOS, allowing developers to build applications specifically for Ledger's operating system.",
    "catalog provider": "A service or repository that distributes software or digital content to users, often including a range of applications or media for easy access and installation.",
    "ci": "Or Continuous Integration. A development practice where all code changes are automatically tested and merged into a shared repository frequently, aiming to prevent integration problems.",
    "clear signing": "A security practice in which the details of a transaction are clearly displayed on the hardware wallet's screen, allowing the user to verify what they are approving.",
    "cli": "Command Line Interface, a text-based interface used to operate software and devices.",
    "crypto asset(s), coin(s), cryptocurrency": "These are the digital assets that can be managed using Ledger devices.",
    "crypto assets": "Digital assets such as cryptocurrencies, tokens, and stablecoins which utilize cryptography for security.",
    "cryptocurrency": "A digital or virtual currency that uses cryptography for security.",
    "dapp browser": "A web browser that is capable of interacting with decentralized applications (DApps) directly from the Ledger Live interface.",
    "dapp plugin": "A plugin designed to work within decentralized applications (DApps) to provide additional functionalities or integration with external services.",
    "debug app": "Applications or tools designed to help developers identify and resolve issues within their software, providing insights into the code's execution and state.",
    "deliverables": "Developers need to provide certain deliverables, including a security audit, icons, a companion wallet, a demo, documentation, support, marketing, and legal materials.",
    "developer mode": "A mode within Ledger Live that enables additional features and settings designed for developer use, often used for testing or debugging purposes.",
    "device application": "Software that runs on a hardware device like Ledger Nano S, Nano X, etc.",
    "device app": "Software that runs on a hardware device like Ledger Nano S, Nano X, etc.",
    "dune dashboard": "A tool or platform that visualizes blockchain data, often used to analyze and report on cryptocurrency transactions and trends.",
    "embedded app": "Applications that are installed on the Ledger device to manage different crypto assets.",
    "embedded plugin": "A software component that integrates into another application (en embedded app) to extend its functionality, used to support additional EVM chains.",
    "ethereum": "A decentralized platform that runs smart contracts: applications that run exactly as programmed without any possibility of downtime, fraud or third-party interference.",
    "experimental apps": "Applications in a preliminary phase of development that are released to gather user feedback and test functionality, which may not yet be fully stable.",
    "firmware": "Software programmed into the read-only memory of a device, providing the low-level control for the device's specific hardware.",
    "fuzzing": "A software testing technique that involves automatically injecting malformed, unexpected, or random data into the inputs of a program to find security vulnerabilities and bugs.",
    "gas fee estimations": "Predictions or calculations of the gas fees required to perform a transaction on a blockchain, helping users understand potential costs.",
    "hardware Wallet": "A physical device designed to securely store cryptocurrency private keys offline, protecting assets from online threats.",
    "hierarchical deterministic wallets": "A type of wallet that uses a single seed to derive many key pairs for managing multiple cryptocurrencies or accounts.",
    "iframe provider": "A service or tool that enables the embedding of external web content into a webpage through an HTML iframe element.",
    "integration": "The process of linking together different computing systems and software applications physically or functionally, to act as a coordinated whole.",
    "integration walkthrough - web usb/hid": "A guide provided by Ledger to help developers understand how to integrate Ledger devices with web applications using USB or HID protocols.",
    "ledger live": "The Ledger application that allows users to manage their cryptocurrency assets and devices.",
    "ledger live integration application form": "A form that developers must fill out to provide information about their project for integration with Ledger Live.",
    "ledger nano s, nano x, and nano s plus": "Different models of Ledger hardware wallets.",
    "ledgerjs": "A JavaScript library developed by Ledger, designed specifically for communication between Ledger devices and web applications, facilitating the integration of Ledger hardware wallets with various crypto services and DApps.",
    "live app": "A software application that runs live on a platform, such as Ledger Live, providing various crypto-related services directly to the user.",
    "local app": "An application that is installed and runs locally on a user's device rather than over the internet, providing benefits in terms of speed and security.",
    "manifest": "A file containing metadata about a software application, which includes information like version, name, permissions, and other configuration details necessary for its integration.",
    "market cap": "The total market value of a cryptocurrency's circulating supply; calculated as the current price multiplied by the number of coins in circulation.",
    "marketing plan": "A document outlining the roadmap, dates, and actions for promoting third-party applications compatible with Ledger devices.",
    "master seed": "A primary key from which all individual cryptographic keys are derived in a wallet, crucial for the security and recovery of a user's assets.",
    "mnemonic": "A memorable sequence of words generated from a specified list, used to derive deterministic wallets.",
    "nano api": "Also known as \"LedgerJS Dedicated App Lib,\" it helps carry out operations with the embedded applications on the Ledger device.",
    "nonce": "A unique number that can only be used once (hence, nonce), typically used in cryptography and blockchain technology to prevent replay attacks and to ensure transactions are processed in an orderly fashion. It is used alter the hash in blockchain transactions",
    "open source": "The Ledger Live code is open source under the MIT license, allowing developers to copy, fork, and modify it. However, for official support in Ledger Live, interaction with Ledger and adherence to their processes is required.",
    "participant integration": "This is the process where Ledger teams (Security, Product, Engineering, and QA) collaborate with external developers. An Agreement Framework is discussed to clarify roles and responsibilities.",
    "platform dev tools": "Development tools tailored to a specific platform, aiding developers in creating applications or services that are optimized for that environment.",
    "postMessage api": "A web API that enables secure communication between windows and iframes in a webpage, allowing them to send data to one another.",
    "protobuf (protocol buffers)": "A method developed by Google for serializing structured data, useful for developing programs to communicate with each other over a wire or for storing data.",
    "release on platforms": "To be officially released by Ledger, the protocol must be included on all five platforms of Ledger Live (Windows, MacOS, Linux, Android, iOS).",
    "review process": "After submitting project information, Ledger will review the application. This can take some time due to the volume of submissions.",
    "repic calls": "Remote Procedure Calls, a technology used in network communications where a computer program causes a procedure to execute in another address space, commonly used in blockchain networks.",
    "scope and technical specificities": "Once the project is reviewed, Ledger will work with the developer to clarify the scope and technical specifics of the project.",
    "sdk": "Or Software Development Kit. A collection of software tools and libraries that developers use to create applications for specific platforms or devices.",
    "secure element": "A highly secure chip that protects cryptographic keys and sensitive data from physical and logical attacks.",
    "security audit": "Device Apps and Plugins must undergo a security audit by one of Ledger's trusted partners to be listed on the Ledger Live \"My Ledger\" section.",
    "support resources": "Information on how users can obtain support, including URLs, email addresses, and phone numbers for third-party applications.",
    "technical specificities": "Details regarding the technical aspects of a blockchain or crypto asset that are relevant for integration with Ledger products.",
    "technical support": "Ledger does not provide technical support or code review to teams that have not been vetted by the Ledger team upfront.",
    "third party services": "Services that are not provided by Ledger but can interact with Ledger devices and Ledger Live.",
    "ticker": "An abbreviation used to uniquely identify traded assets including stocks, bonds, and cryptocurrencies, on exchanges.",
    "transaction": "The action of exchanging cryptocurrencies on a blockchain.",
    "transaction parser": "A tool or software module that interprets and displays the details of blockchain transactions, aiding in debugging and analysis.",
    "transport library": "In the context of Ledger, it refers to software libraries that manage the communication between Ledger devices and applications, ensuring data is correctly sent and received via different transport protocols. Is is part of LedgerJS",
    "true random number generator": "Or TRNG. A device or system that generates numbers from a physical random process, crucial for ensuring high levels of security in cryptographic processes.",
    "tx": "A transaction on the blockchain where assets are transferred between parties or smart contracts are executed.",
    "ux": "Or User Experience. The overall experience of a person using a product such as a website or a computer application, especially in terms of how easy or pleasing it is to use.",
    "validation": "Before starting the development phase, it is crucial to have the scope and technical feasibility of the integration validated by Ledger. Official approval from the Ledger team is required.",
    "wallet api": "An interface that allows developers to interact programmatically with a wallet, including features like sending transactions, fetching balances, and managing accounts.",
    "web3": "A term used to describe a new paradigm for applications on the Internet built using decentralized blockchains-the technology behind cryptocurrencies.",
    "Web3 provider": "A service or library that connects users or applications to a blockchain, facilitating interactions like sending transactions or reading data.",
    "web3modal connect flow": "A user interface component or workflow that facilitates the connection between a user's browser and a blockchain network, typically via a wallet."
};


export { definitions };